version: '3.8'

services:
  movies:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./drf_project/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev